# Use the official Node.js image as base
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy the rest of the application files
COPY . .

EXPOSE 5137

CMD ["npm", "run", "dev"]