services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: rails s -b 0.0.0.0
  web:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    ports:
      - "5137:5137"
    volumes:
      - ./client:/app
      - /app/node_modules


    command: npm run dev